### PR TITLE
Update utils.R

### PR DESCRIPTION
**Pull request by thierrygosselin**
Hi Kevin, I was getting this error since you're new update :
```Error in .verifyOSMulticoreSupport(mc.cores, "mc.cores > 1 is not supported on Windows due to limitation of mc*apply() functions.") : 
  could not find function ".verifyOSMulticoreSupport"
```

And I think I nailed it to this part of the code
Best
thierry

### CODE REVIEW

**Comment by thierrygosselin** [comment]
Not sure it fixes the bug though...

**Comment by kvnkuang** [comment]
Thanks for your request! Yes, it seems like I forgot to remove a temp line I added during development...

**Comment by kvnkuang** [comment]
However, ".verifyOSMulticoreSupport" has been removed from the codebase. Could you please let me know which line triggered the error (stack traceback would be very helpful).

Thanks again for reporting and fixing this!
Kevin

**Comment by thierrygosselin** [comment]
I think the `.verifyOSMulticoreSupport` was a glitch on my end after testing different version. I no longer have an error with v.1.2.4
Thanks
Thierry

**Pull request merged**
